This is an exploratory notebook that looks into medical dataset relevant for predicting heart disease in patients. 
The dataset was downloaded from UC Irvine Machine Learning Repository (https://archive.ics.uci.edu/dataset/45/heart+disease) 

It contains data from 4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach

The dataset contains 303 patients and 14 attributes. 

The attributes are:

 1. age (years)     
 
 2. sex (1 = male; 0 = female)
 
 3. cp  (chest pain type) (1: typical angina | 2: atypical angina | 3: non-anginal pain | 4: asymptomatic)
 
 4. trestbps (resting blood pressure in mm Hg (on admission to the hospital))
 
 5. chol   (serum cholestoral in mg/dl)
 
 6. fbs    (fasting blood sugar > 120 mg/dl)  (1 = true; 0 = false)
 
 7. restecg  (resting electrocardiographic results) (0: normal | 1: having ST-T wave abnormality |2: showing probable or definite left ventricular hypertrophy )
                                                     
 8. thalach (maximum heart rate achieved)
 
 9. exang   (exercise induced angina (1 = yes; 0 = no))
 
 10. oldpeak (ST depression induced by exercise relative to rest)
 
 11. slope   (the slope of the peak exercise ST segment) (1: upsloping | 2: flat | 3: downsloping)
 
 12. ca      (number of major vessels (0-3) colored by flourosopy)
  
 13. thal    (3 = normal; 6 = fixed defect; 7 = reversable defect)
 
 14. num     (diagnosis of heart disease (angiographic disease status)) (0: < 50% diameter narrowing | 1: > 50% diameter narrowing)

In [6]:
import numpy as np
import os
import pandas as pd
import zipfile

notebook_path = os.path.abspath("explore_data.ipynb")
heart_csv_path = os.path.join(os.path.dirname(notebook_path), "heart+disease.zip")
zf = zipfile.ZipFile(heart_csv_path)

header = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num']
df = pd.read_csv(zf.open('processed.cleveland.data'), header=None, names=header)

In [7]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0